# Generated by Django 4.0.1 on 2022-03-08 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('cakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.cake')),
            ],
        ),
    ]
