# Generated by Django 4.0.1 on 2022-02-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Price', models.IntegerField()),
                ('Stock', models.FloatField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Desc', models.TextField()),
                ('Offer', models.FloatField()),
                ('Offer2', models.BooleanField(default=False)),
            ],
        ),
    ]
